from django.urls import path
from . import views

urlpatterns = [
    path('datasets/', views.datasets, name='datasets'),
    path('ethnic/', views.ethnic, name='ethnic'),
    path('datasets/country_year_active/', views.country_year_active, name='country_year_active'),
    path('datasets/year_active/', views.year_active, name='year_active'),
    path('datasets/pgag_basic/', views.pgag_basic, name='pgag_basic'),
    path('country/<int:country_id>/', views.new_country_detail, name='new_country_detail'),
    path('country-browse/', views.country, name='country'),
    path('country/', views.search_country, name='search_country'),
    path('pgag/', views.search_pgag, name='search_pgag'),
    path('pgag/<int:pgag_id>/', views.pgag_detail, name='pgag_detail'),
    path('pgag/<int:pgag_id>/evidence/', views.pgag_evidence, name='pgag_evidence'),
    path('target/', views.target, name='target'),
    path('member/', views.member, name='member'),
    path('member/<int:member_id>/', views.member_detail, name='member_detail'),
    path('type/', views.type, name='type'),
    path('type/<type_name>/', views.type_generic, name='type_generic'),
    path('target/<int:target_oid>/', views.target_detail, name='target_detail'),
    path('', views.welcome, name='welcome'),
    path('link/', views.link, name='link'),
    path('link/<int:link_id>/', views.link_detail, name='link_detail'),
    path('support/', views.support, name='support'),
    path('support/<int:support_id>/', views.support_detail, name='support_detail'),
    path('termtype/', views.termtype, name='termtype'),
    path('termtype/<int:termtype_id>/', views.termtype_detail, name='termtype_detail'),
    path('purpose/', views.purpose, name='purpose'),
    path('purpose/<int:purpose_id>/', views.purpose_detail, name='purpose_detail'),
    path('ethnictarg/', views.ethnictarg, name='ethnictarg'),
    path('ethnictarg/<int:ethnictarg_id>/', views.ethnictarg_detail, name='ethnictarg_detail'),
    path('ethnicmem/', views.ethnicmem, name='ethnicmem'),
    path('ethnicmem/<int:ethnicmem_id>/', views.ethnicmem_detail, name='ethnicmem_detail'),
    path('ethnicpurp/', views.ethnicpurp, name='ethnicpurp'),
    path('ethnicpurp/<int:ethnicpurp_id>/', views.ethnicpurp_detail, name='ethnicpurp_detail'),
    path('imprint/', views.imprint, name="imprint"),
]